### PR TITLE
Feature/collections class

### PR DESCRIPTION
**Pull request by granrothge**
Provides a start of scans collections class that allows pcolor plots and waterfall plots of multiple runs.

### CODE REVIEW

**Comment by pseudocubic** [comment]
First of all, thanks for the PR! I think that this will make a good addition to neutronpy.

I have briefly looked over it and my first impression is good. I will spend some time with it next week to give more complete comments and maybe submit some suggested changes to you.  A couple of things that captured my attention are the docstrings, which will have to be complete before a merge, the class definition, which should be capitalized and inherit `object` (i.e. the "new" Python 3 style class definition), i.e. `Scans(object)`, and the name of the package. 

To address the last point, I'm not sure if `scancollection` is the right name (at the very least, to be consistent with the rest of the package it should be `scan_collection`). With the single class there it might be more appropriate as a module within the data package, but if we can foresee collections of other objects, like materials or instruments for example, then maybe a package named something like `containers` (`collections` would have been my choice, but better to not overlap with the standard library), with the submodule scans like you have it. I am certainly open to suggestions/discussion on this point.

**Comment by granrothge** [comment]
As to the questions of naming I can change it to scan_collection.  I can not think of a case where one would like a collection that can not be fit by the scans_collection and the scan.  Say for an example if I wanted to do a waterfall plot as function of doping concentration.  I think I would add a column for doping to the scan, then a variation by material would then be a scan collection.  I think a collection of objects that would contain scans and other things might be better handled by a higher level collection yet, (maybe a NOSQL database), because your processing chain would likely be vary different.  Say for example if you wanted to constrain an sqw model to both scan data and a magnetic susceptibility measurement,  I think that putting the susceptibility data into a scan would add a lot of overhead.

I'll look into improving the doc strings.

**Comment by granrothge** [comment]
Let me know how you want the module named and I will make the change.  I think the doc string are now ready to go.

**Comment by pseudocubic** [comment]
Thanks for updating the docstrings. Could you also add a one-liner in the top level docstring of the file? 

The class definition should also be changed to `class Scans(object):`

After considering it some more, I think that this would would be better as an addition to the data package, i.e. in `neutronpy/data/scans.py` and add `from .scans import Scans` in the `__init__.py`. I would still keep the tests in a separate file like you have it (but rename to `test_scans.py`), instead of combining it with the data tests.

Could you also rebase to make a more simple commit history?

Otherwise I think this is pretty close to being ready for merge. I will take care of merging the docstrings into the sphinx-built documentation, and updating the changelog myself once we have merged.

**Comment by granrothge** [comment]
Ok so this should be good now.

**Comment by pseudocubic** [comment]
The directory `neutronpy/scancollection` and the file `tests/test_scancollection.py` are still left over after your changes, but once those are gone I should have no problem to merge the PR.

**Comment by granrothge** [comment]
the combination of the rebase, fetch and merge,  brought things back that I had removed.  Sorry.  It should be good now.

**Comment by granrothge** [comment]
Finally, this should be ready.

**Comment by pseudocubic** [comment]
Thanks for the contribution and all your hard work!

**Pull request merged**
